apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-fast-replicated
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: replicated-fast